name: Build GP2040-CE Firmware

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version Tag (optional)'
        required: false
        default: ''
  push:
    branches: 
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    name: Build Firmware
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        board: 
          - Haute42COSMOXMUltra
          # 필요한 경우 추가 보드 설정 가능
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: 'recursive'
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      
      - name: Install System Dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            git \
            cmake \
            gcc-arm-none-eabi \
            build-essential \
            python3-pip
      
      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install cmake
      
      - name: Clone Pico SDK
        run: |
          git clone https://github.com/raspberrypi/pico-sdk.git
          cd pico-sdk
          git submodule update --init
          echo "PICO_SDK_PATH=$PWD" >> $GITHUB_ENV
      
      - name: Configure Build Environment
        run: |
          mkdir -p build
          cd build
          cmake \
            -DCMAKE_POLICY_DEFAULT_CMP0048=NEW \
            -DCMAKE_POLICY_DEFAULT_CMP0069=NEW \
            -DCMAKE_POLICY_VERSION_MINIMUM=3.16 \
            -DSKIP_WEB_BUILD=ON \
            -DBOARD=${{ matrix.board_config }} \
            ..
      
      - name: Build Firmware
        run: |
          cd build
          make -j$(nproc)
      
      - name: Prepare Firmware Package
        run: |
          mkdir -p firmware/${{ matrix.board }}
          find build -name "*.uf2" -exec cp {} firmware/${{ matrix.board }}/ \;
      
      - name: Verify Firmware Files
        run: |
          if [ -z "$(ls -A firmware/${{ matrix.board }}/*.uf2)" ]; then
            echo "No .uf2 files found for ${{ matrix.board }}"
            exit 1
          fi
          ls -l firmware/${{ matrix.board }}/*.uf2
      
      - name: Upload Firmware Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: GP2040-CE_Firmware_${{ matrix.board }}
          path: firmware/${{ matrix.board }}/*.uf2
          retention-days: 30
      
      - name: Generate Release Tag
        if: github.event_name == 'workflow_dispatch' && github.event.inputs.version != ''
        run: |
          echo "RELEASE_TAG=${{ github.event.inputs.version }}" >> $GITHUB_ENV
      
      - name: Create GitHub Release
        if: env.RELEASE_TAG != ''
        uses: softprops/action-gh-release@v1
        with:
          files: firmware/${{ matrix.board }}/*.uf2
          tag_name: ${{ env.RELEASE_TAG }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  notify:
    name: Notify Build Status
    needs: build
    if: failure()
    runs-on: ubuntu-latest
    steps:
      - name: Send Slack Notification
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,eventName,ref,workflow
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
